# Generated by Django 5.0.6 on 2024-06-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_videopost_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='status',
            field=models.CharField(choices=[(-1, 'decline'), (0, 'in process'), (1, 'published')], default=0, max_length=1),
        ),
    ]
