# Generated by Django 5.0.6 on 2024-06-11 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_videopost_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='dislikes',
            field=models.ManyToManyField(default='none', related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='likes',
            field=models.ManyToManyField(default='none', related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='video_views',
            field=models.ManyToManyField(default='none', related_name='video_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
