# Generated by Django 5.0.6 on 2024-06-12 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_videopost_dislikes_alter_videopost_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='video_views',
            field=models.ManyToManyField(blank=True, related_name='video_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
